import type { DailyChallengeSet, PlacementGoal } from "@placepro/shared";

export function buildDemoDailyChallengeSet(
  challengeDate: string,
  goal: PlacementGoal = "product_company"
): DailyChallengeSet {
  return {
    id: "demo-daily-challenges",
    challengeDate,
    placementGoal: goal,
    placementGoalLabel: "Product-based company",
    weakTopics: ["Dynamic Programming", "Graphs", "Quantitative Aptitude"],
    progress: {
      codingScore: 68,
      aptitudeScore: 75,
      interviewScore: 60,
      placementReadiness: 72,
      dailyStreak: 7,
      recentSolvedCategories: ["ARRAYS"],
      weakCategories: ["Dynamic Programming", "Graphs"],
    },
    challenges: [
      {
        id: "demo-dsa-1",
        type: "dsa",
        topic: "Dynamic Programming",
        difficulty: "MEDIUM",
        title: "House Robber",
        prompt:
          "Maximize robbery profit without hitting adjacent houses. Return the maximum amount.",
        hints: ["Classic 1D DP", "Space-optimized recurrence"],
        estimatedMinutes: 25,
        codingSlug: "two-sum",
        completed: false,
      },
      {
        id: "demo-dsa-2",
        type: "dsa",
        topic: "Graphs",
        difficulty: "MEDIUM",
        title: "Number of Islands",
        prompt: "Count islands in a 2D binary grid.",
        hints: ["DFS/BFS"],
        estimatedMinutes: 20,
        completed: false,
      },
      {
        id: "demo-apt-1",
        type: "aptitude",
        topic: "Quantitative Aptitude",
        difficulty: "MEDIUM",
        title: "Aptitude: Percentages",
        prompt: "If 20% of a number is 40, what is 50% of that number?",
        options: ["80", "100", "120", "160"],
        hints: ["Find the number first"],
        estimatedMinutes: 3,
        completed: false,
      },
      {
        id: "demo-apt-2",
        type: "aptitude",
        topic: "Logical Reasoning",
        difficulty: "EASY",
        title: "Aptitude: Logic",
        prompt: "All roses are flowers. Some flowers fade quickly. Valid conclusion?",
        options: [
          "All roses fade quickly",
          "Some roses may fade quickly",
          "No roses fade quickly",
          "All flowers are roses",
        ],
        hints: ["Draw a Venn diagram"],
        estimatedMinutes: 3,
        completed: true,
        completedAt: new Date().toISOString(),
        userAnswer: "Some roses may fade quickly",
        isCorrect: true,
      },
      {
        id: "demo-int-1",
        type: "interview",
        topic: "Technical",
        difficulty: "MEDIUM",
        title: "Interview: OS Concepts",
        prompt: "Explain process vs thread with a real project example.",
        hints: ["Define both", "Give trade-offs"],
        estimatedMinutes: 8,
        completed: false,
      },
      {
        id: "demo-int-2",
        type: "interview",
        topic: "HR",
        difficulty: "EASY",
        title: "Interview: Behavioral",
        prompt: "Tell me about yourself in 90 seconds for a software engineer role.",
        hints: ["Present → past → future", "End with why this company"],
        estimatedMinutes: 5,
        completed: false,
      },
    ],
    completedCount: 1,
    totalCount: 6,
    completionPercent: 17,
    isDayComplete: false,
    xpEarnedToday: 10,
    summary:
      "Today's challenges focus on DP, graphs, aptitude, and interview readiness for product company placements.",
    createdAt: new Date().toISOString(),
  };
}
