import type { InterviewExperienceItem } from "@placepro/shared";

export let demoInterviewExperiences: InterviewExperienceItem[] = [
  {
    id: "exp-1",
    companyName: "Amazon",
    role: "SDE Intern",
    interviewDate: new Date(Date.now() - 7 * 86400000).toISOString(),
    questionsAsked:
      "OA: 2 coding + MCQs. Phone: Two Sum variant, LRU Cache design discussion. Final: Leadership principles + STAR behavioral.",
    difficulty: "HARD",
    tips: "Practice Amazon LP questions with STAR format. OA time management is critical.",
    tags: ["amazon", "oa", "intern", "lp"],
    upvoteCount: 124,
    downvoteCount: 3,
    shareCount: 18,
    commentCount: 12,
    author: { name: "Priya S." },
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    trendingScore: 145,
  },
  {
    id: "exp-2",
    companyName: "Google",
    role: "Software Engineer",
    interviewDate: new Date(Date.now() - 14 * 86400000).toISOString(),
    questionsAsked:
      "Phone screen: graph BFS. Onsite: 4 rounds DSA (medium-hard), 1 system design (URL shortener), 1 googliness.",
    difficulty: "HARD",
    tips: "Think aloud consistently. Draw examples before coding.",
    tags: ["google", "onsite", "system-design"],
    upvoteCount: 89,
    downvoteCount: 1,
    shareCount: 22,
    commentCount: 8,
    author: { name: "Rahul K." },
    createdAt: new Date(Date.now() - 14 * 86400000).toISOString(),
    trendingScore: 110,
  },
  {
    id: "exp-3",
    companyName: "TCS",
    role: "Ninja",
    interviewDate: new Date(Date.now() - 3 * 86400000).toISOString(),
    questionsAsked: "NQT aptitude, coding (array rotation), technical MCQs, HR.",
    difficulty: "MEDIUM",
    tips: "Focus on speed in aptitude. Know basic C/Java output questions.",
    tags: ["tcs", "nqt", "service"],
    upvoteCount: 56,
    downvoteCount: 2,
    shareCount: 5,
    commentCount: 4,
    author: { name: "Ananya M." },
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    trendingScore: 59,
  },
];
